# Copyright 2017 Yunify Inc. All rights reserved.
# Use of this source code is governed by a Apache license
# that can be found in the LICENSE file.

default:
	go run gen_helper.go

clean:
	-rm z_update_version.go
